# Use an official Python runtime as the parent image
FROM python:3.8-slim-buster

# Set the working directory in the container
WORKDIR /app

# Install any needed packages specified in requirements.txt
COPY requirements.txt /app/
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app/

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable for FastAPI to run on port 80
ENV UVICORN_PORT=80
ENV UVICORN_HOST=0.0.0.0

# Run the application when the container launches
CMD ["python", "-m", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

# Steps:

# 1. cd satatlia
# 2. docker build -t satalia_docker_image
# 3. docker run -p 80:80 satalia_docker_image
# 4 Documentation Page: http://localhost:80/docs
